# WZUM NBA projekt cz.2

## Stworzenie modelu predykcji dla all-NBA-team oraz all-rookie-team

### Czyszczenie danych dla all-nba-team

In [32]:
import pandas as pd

In [33]:
all_nba = pd.read_csv("./csv/all-nba-team.csv")
players = pd.read_csv("./csv/players.csv")
rookies = pd.read_csv('./csv/rookies.csv')
all_rookies = pd.read_csv('./csv/rookies_voting.csv')

In [13]:
all_nba = all_nba[["Player","season","Pts Won","Pts Max","Share"]]
all_nba

              Player  season  Pts Won  Pts Max  Share
0      Dwight Howard    2010    610.0    610.0  1.000
1       LeBron James    2010    610.0    610.0  1.000
2        Kobe Bryant    2010    604.0    610.0  0.990
3       Kevin Durant    2010    579.0    610.0  0.949
4        Dwyane Wade    2010    520.0    610.0  0.852
..               ...     ...      ...      ...    ...
538  Zion Williamson    2024     11.0    495.0  0.022
539   Paolo Banchero    2024     10.0    495.0  0.020
540     De'Aaron Fox    2024      9.0    495.0  0.018
541      Bam Adebayo    2024      7.0    495.0  0.014
542    DeMar DeRozan    2024      1.0    495.0  0.002

[543 rows x 5 columns]

In [14]:
players = players.drop(["Unnamed: 0","Rk"], axis=1)
# players

In [15]:
players["Player"]=players["Player"].str.replace("*","",regex=False)

In [16]:
def usun_duplikaty(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row
        
players = players.groupby(["Player","season"]).apply(usun_duplikaty)
players.index = players.index.droplevel()
players.index = players.index.droplevel()

/tmp/ipykernel_5725/556925565.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  players = players.groupby(["Player","season"]).apply(usun_duplikaty)

In [17]:
players.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,season
8525,A.J. Green,SG,23,MIL,35,1,9.9,1.5,3.6,0.424,...,0.2,1.1,1.3,0.6,0.2,0.0,0.3,0.9,4.4,2023
9231,A.J. Green,SG,24,MIL,56,0,11.0,1.5,3.5,0.423,...,0.2,1.0,1.1,0.5,0.2,0.1,0.2,0.9,4.5,2024
4376,A.J. Hammons,C,24,DAL,22,0,7.4,0.8,1.9,0.405,...,0.4,1.3,1.6,0.2,0.0,0.6,0.5,1.0,2.2,2017
8663,A.J. Lawson,SG,22,DAL,15,0,7.2,1.5,2.9,0.500,...,0.4,1.0,1.4,0.1,0.1,0.0,0.2,0.7,3.7,2023
9348,A.J. Lawson,SG,23,DAL,42,0,7.4,1.3,2.9,0.446,...,0.3,0.9,1.2,0.5,0.2,0.1,0.3,0.5,3.2,2024
435,A.J. Price,PG,23,IND,56,2,15.4,2.6,6.3,0.410,...,0.2,1.4,1.6,1.9,0.6,0.1,1.1,0.9,7.3,2010
1043,A.J. Price,PG,24,IND,50,0,15.9,2.3,6.4,0.356,...,0.3,1.1,1.4,2.2,0.6,0.0,1.1,1.2,6.5,2011
1605,A.J. Price,PG,25,IND,44,1,12.9,1.3,4.0,0.339,...,0.3,1.1,1.4,2.0,0.5,0.0,0.7,0.7,3.9,2012
2175,A.J. Price,PG,26,WAS,57,22,22.4,2.8,7.2,0.390,...,0.4,1.6,2.0,3.6,0.6,0.1,1.1,1.3,7.7,2013
2783,A.J. Price,SG,27,MIN,28,0,3.5,0.7,1.6,0.413,...,0.0,0.3,0.4,0.5,0.0,0.0,0.3,0.2,1.6,2014

In [18]:
combined_all_nba = players.merge(all_nba, how = "outer", on = ["Player","season"])
combined_all_nba.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,season,Pts Won,Pts Max,Share
0,A.J. Green,SG,23.0,MIL,35.0,1.0,9.9,1.5,3.6,0.424,...,0.6,0.2,0.0,0.3,0.9,4.4,2023,NaN,NaN,NaN
1,A.J. Green,SG,24.0,MIL,56.0,0.0,11.0,1.5,3.5,0.423,...,0.5,0.2,0.1,0.2,0.9,4.5,2024,NaN,NaN,NaN
2,A.J. Hammons,C,24.0,DAL,22.0,0.0,7.4,0.8,1.9,0.405,...,0.2,0.0,0.6,0.5,1.0,2.2,2017,NaN,NaN,NaN
3,A.J. Lawson,SG,22.0,DAL,15.0,0.0,7.2,1.5,2.9,0.500,...,0.1,0.1,0.0,0.2,0.7,3.7,2023,NaN,NaN,NaN
4,A.J. Lawson,SG,23.0,DAL,42.0,0.0,7.4,1.3,2.9,0.446,...,0.5,0.2,0.1,0.3,0.5,3.2,2024,NaN,NaN,NaN
5,A.J. Price,PG,23.0,IND,56.0,2.0,15.4,2.6,6.3,0.410,...,1.9,0.6,0.1,1.1,0.9,7.3,2010,NaN,NaN,NaN
6,A.J. Price,PG,24.0,IND,50.0,0.0,15.9,2.3,6.4,0.356,...,2.2,0.6,0.0,1.1,1.2,6.5,2011,NaN,NaN,NaN
7,A.J. Price,PG,25.0,IND,44.0,1.0,12.9,1.3,4.0,0.339,...,2.0,0.5,0.0,0.7,0.7,3.9,2012,NaN,NaN,NaN
8,A.J. Price,PG,26.0,WAS,57.0,22.0,22.4,2.8,7.2,0.390,...,3.6,0.6,0.1,1.1,1.3,7.7,2013,NaN,NaN,NaN
9,A.J. Price,SG,27.0,MIN,28.0,0.0,3.5,0.7,1.6,0.413,...,0.5,0.0,0.0,0.3,0.2,1.6,2014,NaN,NaN,NaN

In [19]:
combined_all_nba[["Pts Won", "Pts Max", "Share"]] = combined_all_nba[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [20]:
combined_all_nba = combined_all_nba.apply(pd.to_numeric, errors = "ignore")

/tmp/ipykernel_5725/1801481467.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  combined_all_nba = combined_all_nba.apply(pd.to_numeric, errors = "ignore")

In [21]:
combined_all_nba.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
season       int64
Pts Won    float64
Pts Max    float64
Share      float64
dtype: object

In [22]:
combined_all_nba.to_csv("./csv/all_nba_cleaned.csv")

### Czyszczenie danych dla all-rookie

In [34]:
all_rookie = all_rookies[["Player","season","Pts Won","Pts Max","Share"]]
all_rookie

               Player  season  Pts Won  Pts Max  Share
0       Stephen Curry    2010     58.0     58.0  1.000
1        Tyreke Evans    2010     58.0     58.0  1.000
2    Brandon Jennings    2010     58.0     58.0  1.000
3     Darren Collison    2010     46.0     58.0  0.793
4          Taj Gibson    2010     41.0     58.0  0.707
..                ...     ...      ...      ...    ...
338    Toumani Camara    2024      2.0    198.0  0.010
339    Jordan Hawkins    2024      2.0    198.0  0.010
340        Duop Reath    2024      2.0    198.0  0.010
341     Anthony Black    2024      1.0    198.0  0.005
342     Marcus Sasser    2024      1.0    198.0  0.005

[343 rows x 5 columns]

In [35]:
rookies

,Unnamed: 0,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,...,FG%,3P%,FT%,MP.1,PTS.1,TRB.1,AST.1,STL.1,BLK.1,season
0,0,1,David Andersen,"Oct 27, '09, HOU @ POR",29,1,63,891,147,340,...,0.432,0.346,0.687,14.1,5.8,3.3,0.7,0.2,0.2,2010
1,1,2,Antonio Anderson,"Mar 3, '10, OKC @ DEN",24,1,1,15,1,3,...,0.333,NaN,NaN,15.0,2.0,1.0,0.0,0.0,0.0,2010
2,2,3,Jeff Ayres,"Dec 22, '09, POR @ DAL",22,1,39,405,43,65,...,0.662,NaN,0.900,10.4,2.7,2.5,0.0,0.2,0.4,2010
3,3,4,Rodrigue Beaubois,"Oct 30, '09, DAL @ LAL",21,1,56,700,155,299,...,0.518,0.409,0.808,12.5,7.1,1.4,1.3,0.5,0.2,2010
4,4,5,DeJuan Blair,"Oct 28, '09, SAS vs. NOH",20,1,82,1494,275,495,...,0.556,0.000,0.547,18.2,7.8,6.4,0.8,0.6,0.5,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,1467,97,Victor Wembanyama,"Oct 25, '23, SAS vs. DAL",20,1,71,2106,551,1186,...,0.465,0.325,0.796,29.7,21.4,10.6,3.9,1.2,3.6,2024
1350,1468,98,Cam Whitmore,"Oct 25, '23, HOU @ ORL",19,1,47,880,212,467,...,0.454,0.359,0.679,18.7,12.3,3.8,0.7,0.6,0.4,2024
1351,1469,99,Malik Williams,"Apr 3, '24, TOR @ MIN",25,1,7,107,9,34,...,0.265,0.200,0.000,15.3,2.7,5.4,0.3,0.4,0.6,2024
1352,1470,100,Jalen Wilson,"Nov 1, '23, BRK @ MIA",23,1,43,664,76,179,...,0.425,0.324,0.826,15.4,5.0,3.0,1.0,0.3,0.1,2024
1353,1473,101,Isaiah Wong,"Dec 9, '23, IND @ LAL",23,1,1,4,1,3,...,0.333,0.000,NaN,4.0,2.0,0.0,0.0,0.0,0.0,2024

In [36]:
rookies = rookies.drop(["Unnamed: 0","Rk"], axis=1)

In [37]:
rookies["Player"]=rookies["Player"].str.replace("*","",regex=False)

In [38]:
combined_rookies = rookies.merge(all_rookie, how = "outer", on = ["Player","season"])
combined_rookies.head(20)

,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,3PA,...,MP.1,PTS.1,TRB.1,AST.1,STL.1,BLK.1,season,Pts Won,Pts Max,Share
0,A.J. Green,"Oct 22, '22, MIL vs. HOU",23,1,35,345,53,125,44,105,...,9.9,4.4,1.3,0.6,0.2,0.0,2023,NaN,NaN,NaN
1,A.J. Hammons,"Oct 28, '16, DAL vs. HOU",24,1,22,163,17,42,5,10,...,7.4,2.2,1.6,0.2,0.0,0.6,2017,NaN,NaN,NaN
2,A.J. Lawson,"Nov 16, '22, MIN @ ORL",22,1,15,108,22,44,10,25,...,7.2,3.7,1.4,0.1,0.1,0.0,2023,NaN,NaN,NaN
3,A.J. Price,"Oct 30, '09, IND vs. MIA",23,1,56,865,145,354,60,174,...,15.4,7.3,1.6,1.9,0.6,0.1,2010,NaN,NaN,NaN
4,AJ Griffin,"Oct 23, '22, ATL vs. CHO",19,1,72,1401,248,533,101,259,...,19.5,8.9,2.1,1.0,0.6,0.2,2023,26.0,200.0,0.130
5,Aaron Gordon,"Oct 28, '14, ORL @ NOP",19,1,47,797,93,208,13,48,...,17.0,5.2,3.6,0.7,0.4,0.5,2015,5.0,260.0,0.019
6,Aaron Harrison,"Nov 20, '15, CHO vs. PHI",21,1,21,93,5,19,3,10,...,4.4,0.9,0.7,0.1,0.3,0.0,2016,NaN,NaN,NaN
7,Aaron Henry,"Oct 20, '21, PHI @ NOP",22,1,6,17,1,5,0,1,...,2.8,0.3,0.2,0.0,0.0,0.3,2022,NaN,NaN,NaN
8,Aaron Holiday,"Oct 17, '18, IND vs. MEM",22,1,50,646,105,262,43,127,...,12.9,5.9,1.3,1.7,0.4,0.3,2019,1.0,200.0,0.005
9,Aaron Jackson,"Apr 11, '18, HOU @ SAC",31,1,1,35,3,9,1,4,...,35.0,8.0,3.0,1.0,0.0,0.0,2018,NaN,NaN,NaN
10,Aaron Nesmith,"Dec 25, '20, BOS vs. BRK",21,1,46,669,78,178,40,108,...,14.5,4.7,2.8,0.5,0.3,0.2,2021,NaN,NaN,NaN
11,Aaron Wiggins,"Nov 14, '21, OKC vs. BRK",23,1,50,1209,156,337,42,138,...,24.2,8.3,3.6,1.4,0.6,0.2,2022,NaN,NaN,NaN
12,Abdel Nader,"Oct 18, '17, BOS vs. MIL",24,1,48,522,50,149,23,65,...,10.9,3.0,1.5,0.5,0.3,0.2,2018,NaN,NaN,NaN
13,Adam Flagler,"Feb 23, '24, OKC vs. WAS",24,1,2,14,1,7,1,6,...,7.0,1.5,0.0,2.0,0.0,0.0,2024,NaN,NaN,NaN
14,Adam Mokoka,"Dec 28, '19, CHI vs. ATL",21,1,11,112,12,28,6,15,...,10.2,2.9,0.9,0.4,0.4,0.0,2020,NaN,NaN,NaN
15,Adama Sanogo,"Dec 28, '23, CHI vs. IND",21,1,9,66,14,27,0,0,...,7.3,4.0,4.0,0.0,0.1,0.0,2024,NaN,NaN,NaN
16,Ade Murkey,"Dec 22, '21, SAC vs. LAC",24,1,1,1,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,2022,NaN,NaN,NaN
17,Admiral Schofield,"Oct 23, '19, WAS @ DAL",22,1,33,368,35,92,19,61,...,11.2,3.0,1.4,0.5,0.2,0.1,2020,NaN,NaN,NaN
18,Adonis Thomas,"Mar 1, '14, ORL @ MIA",20,1,6,37,6,14,1,5,...,6.2,2.3,0.5,0.5,0.0,0.0,2014,NaN,NaN,NaN
19,Adreian Payne,"Dec 26, '14, ATL vs. MIL",23,1,32,739,91,220,1,9,...,23.1,6.7,5.1,0.9,0.6,0.3,2015,NaN,NaN,NaN

In [39]:
combined_rookies[["Pts Won", "Pts Max", "Share"]] = combined_rookies[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [40]:
combined_rookies = combined_rookies.apply(pd.to_numeric, errors = "ignore")
combined_rookies

/tmp/ipykernel_5725/2179891004.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  combined_rookies = combined_rookies.apply(pd.to_numeric, errors = "ignore")

,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,3PA,...,MP.1,PTS.1,TRB.1,AST.1,STL.1,BLK.1,season,Pts Won,Pts Max,Share
0,A.J. Green,"Oct 22, '22, MIL vs. HOU",23,1,35,345,53,125,44,105,...,9.9,4.4,1.3,0.6,0.2,0.0,2023,0.0,0.0,0.000
1,A.J. Hammons,"Oct 28, '16, DAL vs. HOU",24,1,22,163,17,42,5,10,...,7.4,2.2,1.6,0.2,0.0,0.6,2017,0.0,0.0,0.000
2,A.J. Lawson,"Nov 16, '22, MIN @ ORL",22,1,15,108,22,44,10,25,...,7.2,3.7,1.4,0.1,0.1,0.0,2023,0.0,0.0,0.000
3,A.J. Price,"Oct 30, '09, IND vs. MIA",23,1,56,865,145,354,60,174,...,15.4,7.3,1.6,1.9,0.6,0.1,2010,0.0,0.0,0.000
4,AJ Griffin,"Oct 23, '22, ATL vs. CHO",19,1,72,1401,248,533,101,259,...,19.5,8.9,2.1,1.0,0.6,0.2,2023,26.0,200.0,0.130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,Zoran Dragić,"Nov 15, '14, PHO @ LAC",25,1,16,75,11,30,3,14,...,4.7,1.8,0.5,0.3,0.1,0.0,2015,0.0,0.0,0.000
1350,Zylan Cheatham,"Nov 16, '19, NOP @ MIA",24,1,4,51,6,9,0,1,...,12.8,3.0,2.3,0.8,0.3,0.3,2020,0.0,0.0,0.000
1351,Álex Abrines,"Oct 26, '16, OKC @ PHI",23,1,68,1055,134,341,94,247,...,15.5,6.0,1.3,0.6,0.5,0.1,2017,4.0,200.0,0.020
1352,Ángel Delgado,"Feb 7, '19, LAC @ IND",24,1,2,15,1,5,0,0,...,7.5,1.5,2.0,0.0,0.5,0.0,2019,0.0,0.0,0.000
1353,Ömer Aşık,"Oct 27, '10, CHI @ OKC",24,1,82,989,78,141,0,0,...,12.1,2.8,3.7,0.4,0.2,0.7,2011,6.0,58.0,0.103

In [41]:
combined_rookies.dtypes

Player      object
Debut       object
Age          int64
Yrs          int64
G            int64
MP           int64
FG           int64
FGA          int64
3P           int64
3PA          int64
FT           int64
FTA          int64
ORB          int64
TRB          int64
AST          int64
STL          int64
BLK          int64
TOV          int64
PF           int64
PTS          int64
FG%        float64
3P%        float64
FT%        float64
MP.1       float64
PTS.1      float64
TRB.1      float64
AST.1      float64
STL.1      float64
BLK.1      float64
season       int64
Pts Won    float64
Pts Max    float64
Share      float64
dtype: object

In [42]:
combined_rookies.to_csv("./csv/all_rookies_cleaned.csv")